import type { Metadata } from "next";
import PublicHeader from "@/components/public/PublicHeader";


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <>
            <PublicHeader />
            {children}
        </>
    );
}
